version: "3"

services:
  # mysql
  db:
    image: mariadb:10.4.13
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/migrate:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/custom.cnf
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
